version: '3'

services:
  atm_service:
    image: openjdk:8
    container_name: atmservice
    ports:
      - "80:80"
    volumes:
      - "./atm-service/target:/home/atm_service"
    working_dir: /home/atm_service
    command: java -jar atm-service-0.0.1-SNAPSHOT.jar
    restart: unless-stopped

  bank_service:
    image: openjdk:8
    container_name: bankservice
    ports:
      - "81:81"
    volumes:
      - "./bank-service/target:/home/bank_service"
    working_dir: /home/bank_service
    command: java -jar bank-service-0.0.1-SNAPSHOT.jar
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    volumes:
        - "./init-db/init.sql:/data/application/init.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
